server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://${MYSQLHOST:mysql-eec8288-example2871003323-f708.d.aivencloud.com}:${MYSQLPORT:14596}/${MYSQLDATABASE:defaultdb}?useSSL=true&trustServerCertificate=true
spring.datasource.username=${MYSQLUSER:avnadmin}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:myDataHubSuperSecretEncryptionKey2026Secure!}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://leonnimincc.github.io}
